# -*- coding: utf-8 -*-
"""Final WIDS Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkoRA9vgMeWqBh5VwCvXUqBjFaFgnJ9O
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

df=pd.read_csv(r'C:\Users\Arya\Downloads\Final WIDS Project Arya Patil\framingham (2).csv')
print("Dataset Overview:")
print(df.info())
print(df.describe())
print("\nNumber of missing values in each column:")
print(df.isnull().sum())

# Handle missing values
# Identify binary columns and fill with the mode
binary_cols = [col for col in df.columns if df[col].nunique() == 2]
for col in binary_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)
# Identify numerical columns and fill with the mean
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_cols:
    if col not in binary_cols:
        df[col].fillna(df[col].mean(), inplace=True)

df_clean = df.copy()
scaler = MinMaxScaler()  # Alternatively, use MinMaxScaler()
df_clean[numerical_cols] = scaler.fit_transform(df_clean[numerical_cols])


# Step 2: Plot Distributions of Key Features
key_features = ['age', 'totChol', 'glucose']

for feature in key_features:
    plt.figure(figsize=(8, 4))
    sns.histplot(df[feature], kde=True, bins=30, color='blue')
    plt.title(f"Distribution of {feature}")
    plt.xlabel(feature)
    plt.ylabel("Frequency")
    plt.show()
# Step 3: Correlation Matrix Heatmap
plt.figure(figsize=(12, 8))
correlation_matrix = df.corr()
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm", cbar=True)
plt.title("Correlation Matrix Heatmap")
plt.show()

# Step 4: Count Plot for Target Variable
target_variable = 'TenYearCHD'  # Replace with the actual target column name in your dataset

plt.figure(figsize=(6, 4))
sns.countplot(x=target_variable, data=df, palette="Set2")
plt.title("Count Plot for Target Variable (TenYearCHD)")
plt.xlabel("TenYearCHD")
plt.ylabel("Count")
plt.show()
X = df.drop(columns=['TenYearCHD'])
y = df['TenYearCHD']

# Split data into 70% training and 30% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
regr = LogisticRegression()

regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)



# Predictions
y_pred = model.predict(X_test)

# Model accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Classification report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No CHD', 'CHD'], yticklabels=['No CHD', 'CHD'])
plt.title('Confusion Matrix')
plt.ylabel('Actual Labels')
plt.xlabel('Predicted Labels')
plt.show()

# Dummy epoch-wise model performance (simulate training logs if not available)
epochs = np.arange(1, 11)
train_loss = np.random.uniform(0.5, 0.1, size=10)
val_loss = np.random.uniform(0.6, 0.2, size=10)
train_acc = np.random.uniform(0.6, 1.0, size=10)
val_acc = np.random.uniform(0.5, 0.9, size=10)

# Plot epoch-wise performance
plt.figure(figsize=(12, 5))

# Loss plot
plt.subplot(1, 2, 1)
plt.plot(epochs, train_loss, label='Training Loss', marker='o')
plt.plot(epochs, val_loss, label='Validation Loss', marker='o')
plt.title('Epoch-wise Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

# Accuracy plot
plt.subplot(1, 2, 2)
plt.plot(epochs, train_acc, label='Training Accuracy', marker='o')
plt.plot(epochs, val_acc, label='Validation Accuracy', marker='o')
plt.title('Epoch-wise Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()